@extends('frontend.layout.main')
@section('body')
    <!-- Policy Header -->
    <div class="container-fluid bg-light-gradient py-24 mt-5">
        <div class="container py-24">
            <div class="col-12">
                <div class="text-wrapper">
                    <h2 class="fw-900">
                        {{ env('APP_NAME', 'Engagyo') }} | Privacy Policy
                    </h2>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Area Privacy Policy -->
    <div class="container-fluid bg-light-white py-5">
        <div class="container">
            <div class="text-wrapper">
                <h2>Privacy Policy</h2>
                <p>
                    {{ env('APP_NAME', 'Engagyo') }} takes your privacy seriously. Please read the following to learn more
                    about our privacy
                    policy. The federal government and technology industry have developed practical tips to help you guard
                    against Internet fraud, secure your computer and protect your personal information.
                </p>
                <h2>
                    Your Information
                </h2>
                <p>
                    {{ env('APP_NAME', 'Engagyo') }} strives to keep all of our terms, including our privacy policy, to be
                    as simple as possible.
                    {{ env('APP_NAME', 'Engagyo') }} collects information to customize the content you see, fulfill your
                    requests for products and
                    services, improve our services, contact you and for other reasons. {{ env('APP_NAME', 'Engagyo') }} also
                    allows its users to
                    create profiles on the {{ env('APP_NAME', 'Engagyo') }} service. {{ env('APP_NAME', 'Engagyo') }}
                    collects two types of information.
                </p>
                <h2>
                    Information We Explicitly Request
                </h2>
                <p>
                    In order to sign up for a {{ env('APP_NAME', 'Engagyo') }} account and use the service, we require some
                    simple information
                    like a name, email address and/or account authorization via Facebook, Twitter, YouTube, etc. When you
                    enter this information, {{ env('APP_NAME', 'Engagyo') }} stores it so your account may persist, and to
                    help us keep a record
                    of your activities on the service.
                </p>
                <p>
                    Additionally, {{ env('APP_NAME', 'Engagyo') }} may request and collect financial information including
                    tax ID or other
                    information necessary to receive or render payment.
                </p>
                <h2>
                    Information Provided from the Use of Our Service
                </h2>
                <p>
                    Occasionally {{ env('APP_NAME', 'Engagyo') }} will collect certain kinds of information about how/when
                    you use the service,
                    like when you visit a link generated by the {{ env('APP_NAME', 'Engagyo') }} service, or post an ad to
                    a social media account.
                    This information includes:
                </p>
                <ul>
                    <li>
                        <b>Log Information - </b>
                        This can include details of how you used the service/arrived at the service, your IP address, and
                        cookies which may uniquely identify your account or browser.
                    </li>
                    <li>
                        <b>Device Information - </b>
                        In order to better serve our customers, {{ env('APP_NAME', 'Engagyo') }} occasionally collects data
                        about the types of
                        devices which access our service, including hardware models, operating system versions, unique
                        device identification and mobile network information, including phone numbers.
                    </li>
                    <li>
                        <b>Location Information - </b>
                        When you access the {{ env('APP_NAME', 'Engagyo') }} service from a device, or connect a
                        location-aware social media
                        account, {{ env('APP_NAME', 'Engagyo') }} may store location information in order to better serve
                        our users and customers.
                    </li>
                    <li>
                        <b>Local storage - </b>
                        We may collect and store information - including personally identifiable information - locally on
                        your device, using cookies, browser web storage, and application data caches, among other sources.
                    </li>
                </ul>
                <h2>
                    Information Sharing
                </h2>
                <p>
                    {{ env('APP_NAME', 'Engagyo') }} does not rent, sell, or share personal information about you with
                    other people or
                    non-affiliated companies except to provide products or services you've requested, when we have your
                    permission, or when we respond to subpoenas, court orders, or legal process, or to establish or exercise
                    our legal rights or defend against legal claims. If {{ env('APP_NAME', 'Engagyo') }} becomes involved
                    in a merger,
                    acquisition, or any form of sale of some or all of its assets, we will provide notice before personal
                    information is transferred and becomes subject to a different privacy policy.
                </p>
                <p>
                    {{ env('APP_NAME', 'Engagyo') }} may combine information we obtain from business partners or other
                    companies, such as our
                    social media partners, with information {{ env('APP_NAME', 'Engagyo') }} has collected about you in
                    order to serve you better
                    or optimize the functions of the Service.
                </p>
                <h2>
                    Cookies
                </h2>
                <p>
                    {{ env('APP_NAME', 'Engagyo') }} may set and access {{ env('APP_NAME', 'Engagyo') }} cookies on your
                    computer. {{ env('APP_NAME', 'Engagyo') }} uses these cookies in
                    connection with {{ env('APP_NAME', 'Engagyo') }} products and services
                </p>
                <h2>
                    Contents of Items
                </h2>
                <p>
                    The contents of any item that you post directly to the Site, including any text, images, photos, videos
                    and audio, are stored and maintained on our servers in order to publish these items and provide the
                    Service. Your submitted content will be associated with your account.
                </p>
                <h2>
                    Confidentiality and Security
                </h2>
                <p>
                    We limit access to personal information about you to employees or third-party agents who we believe
                    reasonably need to come into contact with that information to provide products or services to you or in
                    order to do their jobs. These individuals are bound by confidentiality obligations and may be subject to
                    discipline, including termination and criminal prosecution, if they fail to meet these obligations.
                </p>
                <h2>
                    Third-Party Sites
                </h2>
                <p>
                    This Policy only applies to the {{ env('APP_NAME', 'Engagyo') }} website and services. We do not
                    exercise control over the
                    sites that our service links to. These other sites may place their own cookies or other files on your
                    computer, collect data or solicit personal information from you. We encourage you to read such privacy
                    policies of any third-party sites you visit. It is the sole responsibility of such third parties to
                    adhere to any applicable restrictions on the disclosure of your personally-identifying information, and
                    {{ env('APP_NAME', 'Engagyo') }} shall not be liable for wrongful use or disclosure of your
                    personally-identifying information
                    by any third party
                </p>
                <h2>
                    Financial Information
                </h2>
                <p>
                    Financial information, including PayPal addresses, Payoneer addresses, credit card details and other
                    financial information is stored using industry-standard security by {{ env('APP_NAME', 'Engagyo') }}
                    and will not be shared
                    with third parties except where such parties are necessary to process payment
                </p>
                <h2>
                    Children
                </h2>
                <p>
                    {{ env('APP_NAME', 'Engagyo') }} is not intended for use by children. Anyone under the age of 13 is not
                    permitted to use the
                    Service and must not attempt to register an account or submit personal information to the Service. We do
                    not knowingly collect any personal information from any person under the age of 13 or allow them to
                    register an account. If {{ env('APP_NAME', 'Engagyo') }} learns it has unknowingly collected this
                    information it is deleted as
                    soon as possible. If you have reason to believe {{ env('APP_NAME', 'Engagyo') }} has collected this
                    data or are a parent or
                    legal guardian who is concerned their child or ward has accessed the service, please contact us by email
                    at help (at) postintelligence.AI
                </p>
                <h2>
                    Change to this Privacy Policy
                </h2>
                <p>
                    {{ env('APP_NAME', 'Engagyo') }} may update this policy to be consistent with industry best practices
                    and to better serve our
                    users and customers. This Privacy Policy may be updated from time to time. We will notify you of any
                    material changes by posting the new Privacy Policy on the Site. You are advised to consult this policy
                    regularly for any changes.
                </p>
            </div>
        </div>
    </div>
@endsection
